# Chamando o objeto Carro
from carro import Carro

fusca = Carro("Volks","Fusca","Azul","Gasolina")
ferrari = Carro("Ferrari","Ferrari 911","Vermelho","Diesel")
tesla = Carro("Tesla","Teslas X5","Prata","Eletrico")

print(f"============")
fusca.ligar()
print(f"============")
fusca.acelerar()
print(f"============")
fusca.frear()
print(f"============")
fusca.desligar()
print(f"============")
ferrari.ligar()
print(f"============")
ferrari.acelerar()
print(f"============")
ferrari.frear()
print(f"============")
ferrari.desligar()
print(f"============")
tesla.ligar()
print(f"============")
tesla.acelerar()
print(f"============")
tesla.frear()
print(f"============")
tesla.desligar()
print(f"============")